# Generated by Django 5.1.3 on 2024-11-19 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatTerceros',
            fields=[
                ('ID_TERCERO', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('TIP_TERCERO', models.IntegerField()),
                ('NOM_TERCERO', models.CharField(max_length=70)),
                ('APE_PATERNO', models.CharField(blank=True, max_length=30, null=True)),
                ('APE_MATERNO', models.CharField(blank=True, max_length=30, null=True)),
                ('FEC_ACTUALIZACION', models.DateField()),
                ('MCA_INHABILITADO', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'CAT_TERCEROS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTipMovimientos',
            fields=[
                ('COD_MOVIMIENTO', models.IntegerField(primary_key=True, serialize=False)),
                ('DESC_MOVIMIENTO', models.CharField(max_length=50)),
                ('TIP_MOVIMIENTO', models.CharField(max_length=1)),
                ('FEC_ACTUALIZACION', models.DateField()),
                ('MCA_INHABILITADO', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'CAT_TIP_MOVIMIENTOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('COD_USUARIO', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('TIP_USUARIO', models.CharField(max_length=3)),
                ('COD_PERMISOS', models.IntegerField()),
                ('COD_PASS', models.CharField(max_length=20)),
                ('FEC_ACTUALIZACION', models.DateField(max_length=15)),
                ('MCA_INHABILITADO', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'CAT_USUARIOS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HisMovimientos',
            fields=[
                ('ID_TERCERO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tasks.catterceros')),
                ('TIP_TERCERO', models.IntegerField()),
                ('FEC_REGISTRO', models.DateField()),
                ('IMP_RETIRO', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('IMP_DEPOSITO', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('FEC_ACTUALIZACION', models.DateField()),
                ('MCA_INHABILITADO', models.CharField(max_length=1)),
                ('COD_MOVIMIENTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.cattipmovimientos')),
                ('COD_USUARIO', models.ForeignKey(db_column='COD_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
            options={
                'db_table': 'HIS_MOVIMIENTOS',
            },
        ),
    ]
