# Generated by Django 4.2.26 on 2025-11-22 06:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tipocambio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTerUsuario',
            fields=[
                ('COD_USUARIO', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ID_TERCERO', models.CharField(max_length=5)),
                ('TIP_TERCERO', models.IntegerField()),
                ('FEC_ACTUALIZACION', models.DateField(blank=True, null=True)),
                ('MCA_INHABILITADO', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'CAT_TER_USUARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('COD_USUARIO', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('TIP_USUARIO', models.CharField(max_length=3)),
                ('CORREO', models.CharField(max_length=50)),
                ('COD_PERMISOS', models.IntegerField()),
                ('COD_PASS', models.CharField(max_length=125)),
                ('FEC_ACTUALIZACION', models.DateField(default=django.utils.timezone.now)),
                ('MCA_INHABILITADO', models.CharField(max_length=1)),
                ('NUM_TEL', models.CharField(blank=True, max_length=20, null=True)),
                ('FOTO_PERFIL', models.ImageField(blank=True, null=True, upload_to=tasks.models.user_directory_path)),
            ],
            options={
                'db_table': 'CAT_USUARIOS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatTipoTercero',
            fields=[
                ('TIP_TERCERO', models.IntegerField(primary_key=True, serialize=False)),
                ('DESC_TIP_TERCERO', models.CharField(max_length=50)),
                ('FEC_ACTUALIZACION', models.DateField(blank=True, null=True)),
                ('MCA_INHABILITADO', models.CharField(max_length=1)),
                ('COD_USUARIO', models.ForeignKey(db_column='COD_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
            options={
                'db_table': 'CAT_TIP_TERCEROS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatTipMovimientos',
            fields=[
                ('COD_MOVIMIENTO', models.IntegerField(primary_key=True, serialize=False)),
                ('DESC_MOVIMIENTO', models.CharField(max_length=50)),
                ('TIP_MOVIMIENTO', models.CharField(max_length=1)),
                ('FEC_ACTUALIZACION', models.DateField(blank=True, null=True)),
                ('MCA_INHABILITADO', models.CharField(max_length=1)),
                ('COD_USUARIO', models.ForeignKey(db_column='COD_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
            options={
                'db_table': 'CAT_TIP_MOVIMIENTOS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CatTerceros',
            fields=[
                ('ID_TERCERO', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('TIP_TERCERO', models.IntegerField()),
                ('NOM_TERCERO', models.CharField(max_length=70)),
                ('APE_PATERNO', models.CharField(blank=True, max_length=30, null=True)),
                ('APE_MATERNO', models.CharField(blank=True, max_length=30, null=True)),
                ('FEC_ACTUALIZACION', models.DateField(blank=True, null=True)),
                ('MCA_INHABILITADO', models.CharField(max_length=1)),
                ('COD_USUARIO', models.ForeignKey(db_column='COD_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
            ],
            options={
                'db_table': 'CAT_TERCEROS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HisMovimientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TIP_TERCERO', models.IntegerField()),
                ('FEC_REGISTRO', models.DateField(blank=True, null=True)),
                ('FEC_ACTUALIZACION', models.DateField(blank=True, null=True)),
                ('IMP_RETIRO', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('IMP_DEPOSITO', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('MCA_INHABILITADO', models.CharField(max_length=1)),
                ('COD_MOVIMIENTO', models.ForeignKey(db_column='COD_MOVIMIENTO', on_delete=django.db.models.deletion.CASCADE, to='tasks.cattipmovimientos')),
                ('COD_USUARIO', models.ForeignKey(db_column='COD_USUARIO', on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
                ('ID_TERCERO', models.ForeignKey(db_column='ID_TERCERO', on_delete=django.db.models.deletion.CASCADE, to='tasks.catterceros')),
            ],
            options={
                'db_table': 'HIS_MOVIMIENTOS',
                'managed': True,
                'unique_together': {('ID_TERCERO', 'TIP_TERCERO', 'COD_MOVIMIENTO', 'FEC_REGISTRO', 'FEC_ACTUALIZACION')},
            },
        ),
    ]
