# Generated by Django 4.2.26 on 2025-12-20 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocambio',
            options={},
        ),
        migrations.RenameField(
            model_name='hismovimientos',
            old_name='id',
            new_name='ID',
        ),
        migrations.AlterUniqueTogether(
            name='hismovimientos',
            unique_together=set(),
        ),
    ]
