# Generated by Django 4.2.26 on 2025-12-20 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tipocambio_options_rename_id_hismovimientos_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hismovimientos',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='tipocambio',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
