# Generated by Django 5.1.3 on 2024-11-19 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_hismovimientos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hismovimientos',
            options={'managed': True},
        ),
    ]
