# Generated by Django 4.2.26 on 2025-12-20 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_hismovimientos_options_alter_tipocambio_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hismovimientos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipocambio',
            options={'managed': True},
        ),
    ]
