# Generated by Django 5.1.3 on 2025-11-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_hismovimientos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatTipoTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIP_TERCERO', models.IntegerField()),
                ('DESC_TIP_TERCERO', models.CharField(max_length=50)),
                ('FEC_ACTUALIZACION', models.DateField(blank=True, null=True)),
                ('MCA_INHABILITADO', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'CAT_TIP_TERCEROS',
                'managed': False,
            },
        ),
    ]
