# Generated by Django 4.2.26 on 2025-12-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_hismovimientos_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_tercero', models.IntegerField()),
                ('tip_tercero', models.IntegerField(default=1)),
                ('fec_registro', models.DateField()),
                ('cod_movimiento', models.CharField(max_length=50)),
                ('imp_retiro', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('imp_deposito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fec_actualizacion', models.DateField()),
                ('mca_inhabilitado', models.CharField(default='N', max_length=1)),
                ('cod_usuario', models.CharField(default='admin', max_length=50)),
            ],
        ),
    ]
