# Generated by Django 4.2.26 on 2025-12-21 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_movimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'managed': False},
        ),
    ]
