# Generated by Django 5.1.3 on 2025-11-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_cattipotercero'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatTerUsuario',
            fields=[
                ('COD_USUARIO', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('ID_TERCERO', models.IntegerField()),
                ('TIP_TERCERO', models.IntegerField()),
                ('FEC_ACTUALIZACION', models.DateField(blank=True, null=True)),
                ('MCA_INHABILITADO', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'CAT_TER_USUARIO',
                'managed': False,
            },
        ),
    ]
