# Generated by Django 4.2.26 on 2025-11-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_catterusuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catterceros',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='catterusuario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cattipmovimientos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cattipotercero',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hismovimientos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
