# Generated by Django 4.2.26 on 2025-11-20 03:30

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_catterceros_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cattipotercero',
            name='id',
        ),
        migrations.AddField(
            model_name='catterceros',
            name='COD_USUARIO',
            field=models.ForeignKey(db_column='COD_USUARIO', default='bmendezar', on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cattipmovimientos',
            name='COD_USUARIO',
            field=models.ForeignKey(db_column='COD_USUARIO', default='bmendezar', on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cattipotercero',
            name='COD_USUARIO',
            field=models.ForeignKey(db_column='COD_USUARIO', default='bmendezar', on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hismovimientos',
            name='id',
            field=models.AutoField(default='bmendezar', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='CORREO',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='FOTO_PERFIL',
            field=models.ImageField(blank=True, null=True, upload_to=tasks.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='usuario',
            name='NUM_TEL',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='catterceros',
            name='FEC_ACTUALIZACION',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catterusuario',
            name='ID_TERCERO',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='cattipmovimientos',
            name='FEC_ACTUALIZACION',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cattipotercero',
            name='TIP_TERCERO',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hismovimientos',
            name='COD_MOVIMIENTO',
            field=models.ForeignKey(db_column='COD_MOVIMIENTO', on_delete=django.db.models.deletion.CASCADE, to='tasks.cattipmovimientos'),
        ),
        migrations.AlterField(
            model_name='hismovimientos',
            name='FEC_ACTUALIZACION',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hismovimientos',
            name='FEC_REGISTRO',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hismovimientos',
            name='ID_TERCERO',
            field=models.ForeignKey(db_column='ID_TERCERO', on_delete=django.db.models.deletion.CASCADE, to='tasks.catterceros'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='COD_PASS',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='FEC_ACTUALIZACION',
            field=models.DateField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='hismovimientos',
            unique_together={('ID_TERCERO', 'TIP_TERCERO', 'COD_MOVIMIENTO', 'FEC_REGISTRO', 'FEC_ACTUALIZACION')},
        ),
    ]
